# The Docker image that will be used to build your app
image: node:lts
# Functions that should be executed before the build script is run
before_script:
  - npm i
  - apt-get update
  - apt-get install php xmlstarlet bash
pages:
  script:
    # Get data from MeetUp and render index.html
    - bash build.sh
    # Dist
    - mv dist public
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
