name: Check

on:
  push:
    branches:
    - main
  schedule:
    - cron: "0 22 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MEETUP_COOKIES: ${{ secrets.MEETUP_COOKIES }}
    steps:
      - uses: actions/checkout@v2
        with:
          node-version: "16.x"

      - name: Before script
        run: |
          npm i 
          sudo apt update
          sudo apt install -y php xmlstarlet bash
          
      - name: Build
        run: |
          echo "MEETUP_COOKIES=${{ secrets.MEETUP_COOKIES }}" >> $MEETUP_COOKIES
          # Get data from MeetUp and render index.html
          ./build.sh
          # Dist
          mv dist public
        env:
          MEETUP_COOKIES: ${{ secrets.MEETUP_COOKIES }}
