name: CI

on:
  push:
    branches:
    - main
  schedule:
    - cron: "0 22 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v2
        with:
          node-version: "16.x"

      - name: Before script
        run: |
          npm i 
          sudo apt update
          sudo apt install -y php xmlstarlet bash
          
      - name: Build
        env:
          MEETUP_COOKIES: ${{ secrets.MEETUP_COOKIES }}
        run: |
          # Get data from MeetUp and render index.html
          ./build.sh
   
      - name: Upload
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -f docs
          git commit -m "$(date +"%F")"
          if ! git diff-index --quiet HEAD --; then
          git push -f origin main
          fi
