name: Check

on:
  push:
    branches:
    - main
  schedule:
    - cron: "0 22 * * *"

env:
  MEETUP_COOKIES: ${{ env.MEETUP_COOKIES }}
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          node-version: "16.x"

      - name: Before script
        run: |
          npm i 
          sudo apt update
          sudo apt install -y php xmlstarlet bash
          
      - name: Build
        run: |
          # Get data from MeetUp and render index.html
          bash build.sh
          # Dist
          mv dist public
